# TODO define per experiment
SAMPLING_RATE = 1000 # Hz
PULSE_FRAMES = 50
KERNEL_PRE_FRAMES = 13
KERNEL_POST_FRAMES = 17
IS_NEGATIVE_GEVI = True
PLOT_CLEANING_STEPS = True

# Paths
CLEAN_PATH = "./clean_movie.tif"
SNAPT_RESULTS_DIR = "./snapt_results"
RAW_RESULTS_DIR = SNAPT_RESULTS_DIR + "/raw"
PCA_RESULTS_DIR = SNAPT_RESULTS_DIR + "/pca"